name: Deploy Docs
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3

      - name: Build Docs
        run: mkdir docs && xcodebuild docbuild -scheme FishjamClient -destination generic/platform=iOS OTHER_DOCC_FLAGS="--transform-for-static-hosting --output-path docs --hosting-base-path ios-client-sdk"

      - name: Install coreutils
        run: brew install coreutils

      - name: Change PATH
        run: echo "/usr/local/opt/coreutils/libexec/gnubin" >> $GITHUB_PATH

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
